name: "🚀 launch"

on:
    push:
        branches: 
            - master

jobs:
    release:
        name: 🚀 run
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.3.4
            
            
