name: "🚀 publish"

on:
    push:
        branches: 
            - master

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.3.4
            - name: 🟢 node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org
            - name: yarn clean
              run: yarn cache clean --force
            - name: yarn install
              run: yarn install
            - name: ✨ yarn build
              run: yarn run build
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: dappetter
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
